title: "Telagamsetty Sabari Tejaswi"
logo: /assets/img/logo.jpeg

description: >
  Computer Science graduate with a strong foundation in software development and a keen interest in Machine Learning and AI.
  Experienced in building scalable backend systems using Java, Python, Spring Boot, and Flask.
  Skilled in developing RESTful APIs and implementing computer vision solutions with OpenCV.
  Eager to contribute to innovative projects at the intersection of data science and real-world problem solving.

theme: jekyll-theme-minimal

