title: <p align="center"> Telagamsetty Tejaswi </p>
logo: /assets/img/logo.jpeg

description: |
  <p align="center">
  <a href="https://linkedin.com/in/sabari-tejaswi-telagamsetty-9580b824b">LinkedIn</a> |
  <a href="https://github.com/Teju17s">GitHub</a>
  
  <br>
  Experienced in building scalable backend systems with Java, Python, Spring Boot, and Flask.  
  Skilled in RESTful API development and computer vision using OpenCV.  
  Passionate about solving real-world problems through AI.
  <br>
  </p>

# Theme settings
theme: jekyll-theme-minimal

# Social links (optional, only shown if layout uses them)
linkedin_username: sabari-tejaswi-telagamsetty-9580b824b
github_username: Teju17s

# Build settings
plugins:
  - jekyll-remote-theme

# Enable remote_theme if using fork of Minimal
remote_theme: pages-themes/minimal@v0.2.0

# Optional - show "Download" button on navbar
show_downloads: false



